### ISSUE TITLE
Error while requiring module nuxt-highcharts: Error: Cannot find module './shared/untyped.a47b2336.cjs'

### ISSUE THREAD

**Issue by Phanuwit** [unjs/untyped#123] opened 2024-01-19 17:58 UTC
### Environment

node v18.18.2 (npm v9.8.1)

### Reproduction

https://github.com/richardeschloss/nuxt-highcharts

### Describe the bug

Unable to use yarn command.
<img width="792" alt="Screenshot 2567-01-20 at 00 57 46" src="https://github.com/unjs/untyped/assets/24976372/dc7d724b-ffe8-4398-93cc-3e9b29307c5f">

**Comment by iford** [comment] 2024-01-19 18:05
I have the same problem.

**Comment by jgourmelen** [comment] 2024-01-19 20:52
same for me

**Comment by stevenhurth** [comment] 2024-01-19 20:52
I put in a hard dependency on 1.4.0 until this gets resolved.

**Comment by galaxyblur** [comment] 2024-01-19 21:25
Getting this with `nuxt prepare` as well

**Comment by galaxyblur** [comment] 2024-01-19 21:32
```
  "overrides": {
    "untyped": "1.4.0"
  }
```
as a temp fix worked for me

**Comment by angelhdzmultimedia** [comment] 2024-01-20 06:25
> ```
>   "overrides": {
>     "untyped": "1.4.0"
>   }
> ```
> 
> as a temp fix worked for me

I put this in package.json and error keeps coming after deleting .nuxt, node_modules and pnpm-lock.yaml.😔

**Comment by markthree** [comment] 2024-01-20 07:06
I think it may be caused by this change → [untyped/commit/1038f03](https://github.com/unjs/untyped/commit/1038f03)

I think I should be able to solve this problem 🥰

**Comment by kasperkronborg** [comment] 2024-01-20 08:10
I believe that's correct @markthree. I was looking at the same thing. There should never be a reason for node to try and resolve a `.d.cts` file.

**Comment by komgrip** [comment] 2024-01-20 09:31
`"resolutions": {
		"**/untyped": "1.4.0"
	}`


	
fix worked for me.

**Comment by samasarin** [comment] 2024-01-20 09:32
we have the same issue.
fixed by adding this to my package.json file:
`"resolutions": {
    "untyped": "=1.4.0"
  },`

**Comment by samasarin** [comment] 2024-01-20 09:35
@pi0 Can you please review this issue.
Our builds are getting failed for this.

![image](https://github.com/unjs/untyped/assets/129737495/f7aef1d1-5a94-44d2-9f60-e5ab7ef306ce)

**Comment by pi0** [comment] 2024-01-20 16:36
Sorry im away from my laptop till tonight. Will check to fix asap.

**Comment by Alkiyogoma** [comment] 2024-01-20 17:17
```
"overrides": {
    "untyped": "1.4.0"
   }
 ``` 

 ### Resolved
  Installed it as dependency instead of override, working now.

**Comment by pi0** [comment] 2024-01-20 17:45
Released 1.4.2 sorry for inconveniences 🙏

https://github.com/unjs/untyped/releases/tag/v1.4.2

**Closed** 2024-01-20 21:13 UTC

**Comment by jgourmelen** [comment] 2024-01-25 11:15
thanks !!
